[project]
name = "chess-openings"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "chess>=1.11.2",
    "huggingface-hub>=1.20.1",
    "ipykernel",
    "matplotlib>=3.11.0",
    "nbformat>=5.10.4",
    "networkx>=3.6.1",
    "numpy>=2.4,<2.5",
    "pandas>=3.0.3",
    "plotly",
    "pyarrow>=24.0.0",
    "tqdm>=4.68.3",
    "umap-learn",
]
